### ISSUE TITLE
Сделать статистку более responsible

### ISSUE THREAD

**Issue by Nihisil** [MahjongPantheon/Rheda#6]
Сейчас страница последних игр выглядит не очень приглядно на мобильных девайсах

**Comment by ctizen** [comment]
Ее переверстать бы, по-хорошему. И выкинуть бутстрап к чертям собачьим. Мобильный клиент вовсю флексбоксы использует, например.

**Comment by ctizen** [comment]
Хотя с другой стороны, на первое время возможно будет достаточно отдельной css-ки на media-query типа (width<768)

**Comment by ctizen** [comment]
Готово же
