### ISSUE TITLE
Вариант оптимизации для текстовых логов

### ISSUE THREAD

**Issue by ctizen** [MahjongPantheon/Rheda#8]
Предложение для оптимизации. 

Завести все комбинации на кнопки, чтобы при заполнении пайфу не нужно было самому (копипаста или руками) вводить их. Тоже самое можно сделать с игроками, например для удобства заполнения - вводишь игроков во временные поля и просто по кнопке добавляешь их в нужные места (места выплат).

**Comment by ctizen** [comment]
Предложение от почетного донатера из Архангельска :)

**Comment by Nihisil** [comment]
Может лучше автокомплит?

**Comment by ctizen** [comment]
Надо подумать. Мотивация в принципе понятна, но как именно это реализовывать - пока не ясно. Ну и приоритет у этого добра не горящий.

**Comment by Nihisil** [comment]
Автокомплит работающий в зависимости от позиции. Где игрока вставить, там подсказка игрока. Где яку, там яку. И выплаты тоже чтоб подсказывал (3han 30fu and etc.)

**Comment by ctizen** [comment]
https://pantheon.myjetbrains.com/youtrack/issue/RHEDA-9
